<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net45;net472</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="App_Data\ApiSettings\apiSettings.xml" />
    <None Remove="App_Data\dataMaskingSettings.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="App_Data\ApiSettings\apiSettings.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="App_Data\dataMaskingSettings.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="RestSharp" Version="105.2.3" />
    <PackageReference Include="System.Runtime.Caching" Version="4.7.0" />
  </ItemGroup>

</Project>
